SCREEN_WIDTH = 288
SCREEN_HEIGHT = 512
FPS = 30
SCREEN_BG_COLOUR = "red"

CIRCLE_FILE = "objects/circle.py"
CIRCLE_X = SCREEN_WIDTH / 2
CIRCLE_Y = SCREEN_HEIGHT / 2 - 50
CIRCLE_RADIUS = 200
CIRCLE_OPACITY = 175